#!/bin/bash
set -e

command_string="composer -vvv"

if [ -n "$action_ssh_key" ]
then
	echo "Storing private key file for root"
	mkdir -p /root/.ssh
	ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
	ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
	ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
	echo "$action_ssh_key" > /root/.ssh/id_rsa
	echo "$action_ssh_key_pub" > /root/.ssh/id_rsa.pub
	chmod 600 /root/.ssh/id_rsa
fi

ssh -vvv git@github.com
echo "Test has completed"
exit

if [ -n "$action_command" ]
then
	command_string="$command_string $action_command"
fi

case "$action_interaction" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-interaction"
	;;
	*)
		echo "Invalid input for action argument: interaction  (must be yes or no)"
		exit 1
	;;
esac

case "$action_suggest" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-suggest"
	;;
	*)
		echo "Invalid input for action argument: suggest (must be yes or no)"
		exit 1
	;;
esac

case "$action_dev" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-dev"
	;;
	*)
		echo "Invalid input for action argument: dev (must be yes or no)"
		exit 1
	;;
esac

case "$action_progress" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-progress"
	;;
	*)
		echo "Invalid input for action argument: progress (must be yes or no)"
		exit 1
	;;
esac

case "$action_quiet" in
	yes)
		command_string="$command_string --quiet"
	;;
	no)
		# Default behaviour
	;;
	*)
		echo "Invalid input for action argument: quiet (must be yes or no)"
		exit 1
	;;
esac

if [ -n "$action_args" ]
then
	command_string="$command_string $action_args"
fi

echo "Command: $command_string"
eval "$command_string"