#!/bin/bash
set -e

command_string="composer"

if [ -n "$action_ssh_key" ]
then
	echo "Storing private key file for root"
	mkdir -p /root/.ssh
	ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
	ssh-keyscan -t rsa gitlab.com >> /root/.ssh/known_hosts
	ssh-keyscan -t rsa bitbucket.org >> /root/.ssh/known_hosts

	if [ -n "$action_ssh_domain" ]
	then
		ssh-keyscan -t rsa "$action_ssh_domain" >> /root/.ssh/known_hosts
	fi

	echo "$action_ssh_key" > /root/.ssh/id_rsa
	echo "$action_ssh_key_pub" > /root/.ssh/id_rsa.pub
	chmod 600 /root/.ssh/id_rsa

	echo "PRIVATE KEY:"
	md5sum /root/.ssh/id_rsa
	echo "PUBLIC KEY:"
	md5sum /root/.ssh/id_rsa.pub
fi

if [ -n "$action_command" ]
then
	command_string="$command_string $action_command"
fi

case "$action_interaction" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-interaction"
	;;
	*)
		echo "Invalid input for action argument: interaction  (must be yes or no)"
		exit 1
	;;
esac

case "$action_suggest" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-suggest"
	;;
	*)
		echo "Invalid input for action argument: suggest (must be yes or no)"
		exit 1
	;;
esac

case "$action_dev" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-dev"
	;;
	*)
		echo "Invalid input for action argument: dev (must be yes or no)"
		exit 1
	;;
esac

case "$action_progress" in
	yes)
		# Default behaviour
	;;
	no)
		command_string="$command_string --no-progress"
	;;
	*)
		echo "Invalid input for action argument: progress (must be yes or no)"
		exit 1
	;;
esac

case "$action_quiet" in
	yes)
		command_string="$command_string --quiet"
	;;
	no)
		# Default behaviour
	;;
	*)
		echo "Invalid input for action argument: quiet (must be yes or no)"
		exit 1
	;;
esac

if [ -n "$action_args" ]
then
	command_string="$command_string $action_args"
fi

echo "Command: $command_string"
eval "$command_string"